### ISSUE TITLE
Add quick-share links to VUIDs

### ISSUE THREAD

**Issue by magcius** [KhronosGroup/Vulkan-Site#10]
VUIDs do have individual IDs, e.g. https://registry.khronos.org/vulkan/site/spec/latest/chapters/fxvertex.html#VUID-VkVertexInputBindingDescription-binding-00618

but there's no quick-link to share directly to them. Additionally, the fixed header seems to overlap them in some cases.

**Comment by oddhack** [comment]
I'm porting over a Ruby asciidoc extension to the asciidoctor.js pipeline that Antora uses, which will fix this. Running into a few problems and consulting the Asciidoctor Zulip chat, but should have it done soon.

**Comment by oddhack** [comment]
I believe this is fixed in the new site build. If you agree, please close this issue.

**Comment by magcius** [comment]
Lovely! Thank you so much.
