### ISSUE TITLE
Broken code formatting around https://registry.khronos.org/vulkan/site/spec/latest/chapters/memory.html near findProperties

### ISSUE THREAD

**Issue by nanokatze** [KhronosGroup/Vulkan-Site#11]
![image](https://user-images.githubusercontent.com/25141408/230512769-a188ba4c-1216-4d8e-8031-a70d363d4531.png)

**Comment by oddhack** [comment]
Thanks. I'm going to have to port more of our custom Ruby asciidoctor extensions over to JavaScript to get this formatted correctly - overlooked this one.

**Comment by oddhack** [comment]
@nanokatze I believe this has been fixed now - please take a look and close this issue if you agree, or let me know where you're still seeing the problem.
