### ISSUE TITLE
Screen Overrun for Help Menu

### ISSUE THREAD

**Issue by mohanasra** [KhronosGroup/Vulkan-Site#15]
The help menu contents go beyond the screen. Please check the screenshot

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/23220132/66145f0d-856c-498b-a752-383125ddc739)

**Comment by JakeMerdichAMD** [comment]
Setting the relevant menu from `class="navbar-dropdown"` to `class="navbar-dropdown is-right"` should fix this.

**Comment by gpx1000** [comment]
Fixed with #18
