### ISSUE TITLE
Vulkan logo causes whole navbar to be garbled on firefox

### ISSUE THREAD

**Issue by JakeMerdichAMD** [KhronosGroup/Vulkan-Site#17]
On firefox (windows 115.0.2), the navbar is very garbled, which means search is unusable.

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/60545770/21cda3ed-bf17-4d3a-94c7-8447198b2e55)
![image](https://github.com/KhronosGroup/Vulkan-Site/assets/60545770/1c9f3d84-8916-4726-92e2-031b8bf6c523)

This seems to be running afoul of this firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1339115

The gist is that the 100% height of the logo is causing firefox to calculate its minimum width as much larger than it should be and causing all other items to shrink dramatically. A workaround is to use an equivalent explicit height (ie. 2.5rem) via css instead of 100%.

**Comment by oddhack** [comment]
@JakeMerdichAMD is this still happening for you on the current docs.vulkan.org site? It looks OK in 103.13.0esr on Debian, for me. If it's fixed, please close this.

**Comment by JakeMerdichAMD** [comment]
Works for me!
