### ISSUE TITLE
Add syntax highlighters for shading languages

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Site#2]
In some spots like the [HLSL chapter](https://registry.khronos.org/vulkan/site/guide/latest/hlsl.html#_hlsl) of the Vulkan guide we have GLSL and HLSL code snippets. It would be nice if we could get syntax highlighting added for those too (which is already the case for C/C++ code snippets).

**Comment by SaschaWillems** [comment]
It looks like Asciidoctor also supports highlight.js, which is pretty common: https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/highlightjs/

hightlight.js supports e.g. glsl out of the box. For hlsl we would need to include a custom highlighter based on highlight.js: https://github.com/highlightjs/highlightjs-hlsl

Did that for a branch of Vulkan Tutorial, so if you want I can take a look at it.

**Comment by oddhack** [comment]
@SaschaWillems I setup a fork of the Antora UI in https://github.com/KhronosGroup/antora-ui-khronos and if you are able to take a look at the highlight GLSL/HLSL integration that would be great. Superficial examination suggests that src/js/vendor/highlight.bundle.js may need to have those languages registered, but that's just a guess.

N.b. to make this have any effect on the demo site I have to rebuild the UI bundle in that repo, then copy it over here, then rebuild the site and push it to the webserver, not at all automatic ATM. So debugging might get pretty tedious.

**Comment by oddhack** [comment]
> @SaschaWillems I setup a fork of the Antora UI in https://github.com/KhronosGroup/antora-ui-khronos and if you are able to take a look at the highlight GLSL/HLSL integration that would be great. Superficial examination suggests that src/js/vendor/highlight.bundle.js may need to have those languages registered, but that's just a guess.
> 
> N.b. to make this have any effect on the demo site I have to rebuild the UI bundle in that repo, then copy it over here, then rebuild the site and push it to the webserver, not at all automatic ATM. So debugging might get pretty tedious.

I've added the glsl source highlighter - you can see it in the SPIR-V sample code in https://registry.khronos.org/vulkan/site/spec/latest/chapters/pipelines.html#VkSpecializationMapEntry (which is tagged as glsl source - probably because nobody has defined a SPIR-V grammar for the various source highlighters we use in the spec build).

Incorporating the hlsl grammar will be a bit more involved since it's in a separate JS package from highlight.js itself, but looks manageable.

**Comment by SaschaWillems** [comment]
Thanks. I gave this a shot some time ago. and adding in the HLSL grammar is indeed a bit more involved. It actually seems to be easier if we do our own highlighting, which is easier to integrate.

**Comment by oddhack** [comment]
Do you know if the HLSL grammar is available as a node module? That seems like an easier way of integrating it with the site UI but I don't see any references to that on the github site.

**Comment by oddhack** [comment]
I think once I figure out how to add the highlight grammar .js to the Antora UI and add references to it from their highlight configuration script, it should just work. But it's pretty opaque because all the JS in the default UI gets sent through a minification / bundling / obscuration filter before being packaged for Antora, so trying to get clarity on how to properly require the new grammar from inside that highlighter setup.

Alternatively the HLSL grammar could be published as a node module and added to the UI setup in which case I think it would be straightforward, but the github site seems pretty dead so we might have to create our own module instead.

**Comment by oddhack** [comment]
Making some progress. I can get hlsl.js into the Antora UI build now, but it is getting a ton of eslint errors on the file (and also on the minified version). Unfortunately I don't think we can get away with including this highlighter without making changes to upstream.

**Comment by SaschaWillems** [comment]
As an alternative we could write our own highlighter. Doing this doesn't seem to complicated (gave it a try on a local version of this repo), and in that process we could also add newer and Vulkan related HLSL tokens to the highlighter.

**Comment by oddhack** [comment]
I believe this is working now - see https://registry.khronos.org/vulkan/site/guide/latest/hlsl.html#_hlsl . That might be the only example of HLSL in the current documents in the site build but there is some highlighting going on. Had to convert hlsl.js to CJS to get it to fit into the Antora UI bundle.

Please close if you agree this fixes the issue.

**Comment by oddhack** [comment]
> As an alternative we could write our own highlighter. Doing this doesn't seem to complicated (gave it a try on a local version of this repo), and in that process we could also add newer and Vulkan related HLSL tokens to the highlighter.

I'm fine with updating src/js/vendor/hlsl.js however seems appropriate. The file is so tiny it's hardly worth trying to synchronize with upstream, which looks pretty dead in any event. Speaking of which, is "POSITIONT" actually an HLSL keyword or a typo in the upstream?

**Comment by SaschaWillems** [comment]
Thank you very much for adding this. Highlighting works fine and looks great 👍 

> Speaking of which, is "POSITIONT" actually an HLSL keyword, or a typo in the upstream?

Indeed looks like a typo. The position keywords (e.g. POSITION0) are properly highlighted though. But in general as you said that highlighter is a bit dated, and also doesn't know about any of the Vulkan keywords or newer HLSL stuff. With it now being part of this project I'll take a look and try to add in new stuff.
