### ISSUE TITLE
Add a Favicon

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Site#27]
This is very minor, but it would be nice if we could add a Favicon to the documentation site, so it'll show up with that icon in the browser tab like other Vulkan sites do too:

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/10283127/2eaf01fd-9622-435f-8186-3c0077c9b4fe)

**Comment by KhronosWebservices** [comment]
It would be good to add a complete set of headers and icons to ensure we get full coverage across all devices. Headers would be along the lines of:

```
<link rel="apple-touch-icon" sizes="180x180" href="{{{uiRootPath}}}/img/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="{{{uiRootPath}}}/img/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="{{{uiRootPath}}}/img/favicon-16x16.png">
<link rel="manifest" href="{{{uiRootPath}}}/img/site.webmanifest">
<link rel="mask-icon" href="{{{uiRootPath}}}/img/safari-pinned-tab.svg" color="#a41e22">
<meta name="msapplication-TileColor" content="#ffc40d">
<meta name="theme-color" content="#ffffff">
```

Marty now has the complete icon set to match these headers.
