### ISSUE TITLE
Docs site "swallows" some spaces

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Site#29]
Not sure why this happens, but while looking through the spec part of the docs site, I noticed that there are several spots where spaces seem to get lost in the conversion.

E.g. in the Fundamentals chapter:

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/10283127/a7451183-d4d9-4cf0-8517-61dfbcf5efc7)

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/10283127/fcf1cc64-95fe-4622-8bd3-fcb2fdb2db52)

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/10283127/86125602-41b1-45c5-a191-c8e7e7bd1f9b)

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/10283127/e644f6ae-7677-408b-9020-540ddba9b73b)

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/10283127/46c87110-d335-4c95-9529-1728d207e8b0)

It looks like this happening for links that have a line break in them.

From what I was able to gather this seem to be caused when the link text has a line break:

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/10283127/b697c391-6549-4496-acd6-6f7b9141e8e4)

Instead of the line break getting interpreted as a space, it jut gets removed.

The Memory Model chapter suffers a lot from this, many links in there are missing those spaces.

@oddhack: This seems to affect a lot of places in the spec. We may want to fix before going public with it.

**Comment by oddhack** [comment]
Will need a tweak to the script that converts to Antora structure, should not take long.

**Comment by oddhack** [comment]
This is fixed in the conversion script, though per #35 I have a hard time actually viewing the new files.
