### ISSUE TITLE
Update the landing page

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Site#34]
We want to update the landing page. Right now it contains slightly outdated information.

It would be great if we could turn it into a small information page that helps people on how to use the documentation project and what it consists of.

@gpx1000, @marty-johnson59 and @saschawillems are currently writing up a draft for that.

**Comment by oddhack** [comment]
I made some minor changes to the landing page per #41 and a few other things, and build a new site updated from the latest .267 spec revision.

One thing that might be handy in the new "Site Information" section is a link to the GH Pages where the CI builds are published. I hunted around about 10 minutes and could not find it, although the CI action to publish is succeeding. But know little about Pages or github.io.

**Comment by marty-johnson59** [comment]
Addressed - suggest closing
