### ISSUE TITLE
Logo upper left

### ISSUE THREAD

**Issue by outofcontrol** [KhronosGroup/Vulkan-Site#36]
To better align the logo, I've attached (it's white so you probably won't see it, but it's there) an .svg of the vulkan logo trimmed. This might help nudge it over to the left a bit more using this css, in place of what is currently used:

```
.navbar-brand .navbar-item:first-child {
  flex-wrap: wrap;
  line-height: 1;
  max-height: 4.5rem;
  padding: 10px 0;
  align-content: center;
  margin: 0;
}
```
![Vulkan_White_Dec16_trimmed](https://github.com/KhronosGroup/Vulkan-Site/assets/69415/86b9ebd2-a98a-490d-8147-f1dd590ce758)

**Comment by oddhack** [comment]
@outofcontrol did we already do this? It appears that the logo is pretty well left-aligned ATM but I don't recall adding this to the UI - maybe @gpx1000 did?

**Comment by gpx1000** [comment]
Yes, sorry this is done.
