### ISSUE TITLE
Include Vulkan API spec revision number in the site

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Site#41]
@saschawillems requested (in an internal discussion) that we include the Vulkan API spec revision (e.g. the full 1.3.266 or whatever the latest update is) in the site. Presumably also the "1.3 + all extensions" labelling. In the asciidoc build this shows on the title page, but Antora doesn't generate a title page. Couple of options:

* Add to the landing (default) page https://docs.vulkan.org/spec/latest/index.html, perhaps along with versioning for other components of the site
* Add to the introduction page https://docs.vulkan.org/spec/latest/chapters/introduction.html, as the closest thing to a title page specific to the API spec
* Add to the site nav / title bar, probably in the "Specs" dropdown menu that just says "Vulkan 1.3" right now. This is more complex because it means modifying the UI - probably the right approach would be to generate an overlay for the part of the UI containing this number during the spec build.
* Potentially the component could be versioned (so the revision would show up in the component selection menu in the lower left), but I'm strongly against that because (a) it is a logistical and resource nightmare to maintain old revisions in a buildable form (b) not maintaining them breaks external links into the site when updating the revision number. N.b. LunarG SDK does something like this today, though only for the revisions they ship SDKs for and only for the asciidoc builds.

I don't have strong opinions about this except that the last option is not viable - just mentioned for completeness else someone else would bring it up.

**Comment by SaschaWillems** [comment]
I'm all for a simple solution too. I don't think it's that important, but esp. for the spec it's nice to see what spec version the documentation is based on. So from my pov the spec version on e.g. the landing or introduction page is perfectly fine.

**Comment by oddhack** [comment]
docs.vulkan.org/ site index page has been updated with minor changes to the landing page, including the full spec revision. If further changes are needed please reopen.
