### ISSUE TITLE
Location of GH Pages site build output

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/Vulkan-Site#49]
@gpx1000 could you say how to find where the GH Pages build output is being published?

**Comment by gpx1000** [comment]
https://github.com/KhronosGroup/Vulkan-Site/settings/pages

Just a few settings away from having it publish.

**Comment by oddhack** [comment]
I turned on the gh-pages branch and it seems to be publishing at https://github.khronos.org/Vulkan-Site/spec/latest/index.html . I haven't looked at the CI setup - will this autoupdate for every commit to main branch? Reopen if there are problems.
