### ISSUE TITLE
[New Docs] Unused horizontal space

### ISSUE THREAD

**Issue by darksylinc** [KhronosGroup/Vulkan-Site#5]
It's easy to see on a 16:9 aspect ratio when zooming out:

![Screenshot_2023-04-05_13-40-07](https://user-images.githubusercontent.com/3395130/230147457-b113f08a-c38a-4c59-98db-7b9520f0e392.png)

Here we can see that the right panel is in the middle of the monitor, while the blocks of code in the middle require scrollbars.

The blocks of code in the middle could easily cover the entire space and thus get rid of the scrollbars, while the right panel could be moved further to the right as there still is navigable space.

**Comment by Cyphall** [comment]
The `Contents` block should probably be anchored to the right side of the page, allowing the main middle block to span the remaining width.

**Comment by SaschaWillems** [comment]
We'll take a look at this. It's a simple change in the CSS.

**Comment by SaschaWillems** [comment]
That's true. It's very much a matter of teste. I prefer full width too, but others may not.

**Comment by marty-johnson59** [comment]
Hi @oddhack, we discussed this today and prevailing opinion is that we should grow the max-width allowing folks to make huge windows if they prefer... It would also address the table size issue above.  Is this something you can do?  If readability is a concern, folks can just shrink the window - but others seem to prefer using all your real estate..

**Comment by Dolkar** [comment]
Shrinking the window is cumbersome if you want to have it open as just another tab on the browser.
In my opinion the most readable and compatible format is one that the current spec pages are already using: content around 1000 pixels wide and centered.

**Comment by oddhack** [comment]
N.b. this will not affect the site until the next update, which will probably be 2024-02-02.
