### ISSUE TITLE
Table of contents overlaping with table.

### ISSUE THREAD

**Issue by qbojj** [KhronosGroup/Vulkan-Site#58]
Some of longer tables are overlapping with the table of contents.

E.g:
https://docs.vulkan.org/spec/latest/chapters/videocoding.html#decode-h264-requirements 
![image](https://github.com/KhronosGroup/Vulkan-Site/assets/105227351/7fe7fea2-f2b1-43fe-8319-fef39ac12130)

**Comment by SaschaWillems** [comment]
Duplicate of #21

**Comment by qbojj** [comment]
OK didn't see
