### ISSUE TITLE
Going through all instances of X

### ISSUE THREAD

**Issue by marty-johnson59** [KhronosGroup/Vulkan-Site#60]
Moved over from Antora repo (see comments on issue#5) - from Shahbaz: 

The all-in-one-page spec is horribly slow to load, but it does give one ability that the chunked spec (or the antora version) doesn't. You can go through all instances of some token over the whole spec.

With GL, extensions were easy to inspect in one aspect at least; you had the text of the whole extension all together somewhere. Someone implementing / using the extension could get all the details that are needed from that.

With Vulkan, that's nearly impossible without grepping through the source. The ifdefs (which are the only mark of what text an extension affects) disappear from the output, so you can't really tell from the built spec where exactly an extension touches. That makes it easy to miss things. That said, at least going through the whole spec and looking at matches of someTokenFromExtension would get you 95% of the way.

I'm not sure what a good way would be to do that in a chunked build, but something like this could work:

 ________________________            ____
| someTokenFromExtension |  ◀ Match | 12 | / 67 ▶
 ------------------------            ----

Where you can enter someTokenFromExtension in the search box (that's the ASCII art box), and get a chance to flip through all the matches one by one (with the left/right triangle buttons) (or jump to a match (by editing the match number, the other ASCII art box))

**Comment by oddhack** [comment]
Duplicates #55
