### ISSUE TITLE
Poor readability of grey text on grey background in VU boxes

### ISSUE THREAD

**Issue by marty-johnson59** [KhronosGroup/Vulkan-Site#61]
Moved over from Antora repo (see comments on issue#3) - from DanielS

I'm not sure if this is the correct place for internal issues related to the new Vulkan Documentation Project Demo site, but I wanted to call attention to the somewhat poor contrast of text vs. background in the VU boxes on the new site. VUs are already notoriously dense in terms of both verbiage and actual information content, so I would like to suggest a lighter background color for VU boxes.

**Comment by oddhack** [comment]
Duplicates #56
