### ISSUE TITLE
Some links in the spec navigation could be removed

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Site#67]
There are some links in the navigation of the spec part of the docs site that could be removed:

- This seems to be some stub that feels out-of-place: https://docs.vulkan.org/spec/latest/proposals/index.html
- Having the extension proposal template IMO doesn't make a lot sense imo either: https://docs.vulkan.org/spec/latest/proposals/proposals/template.html

Very minor, but maybe something that can be easily changed.

Possible related to #54

**Comment by oddhack** [comment]
I would be OK with taking the template out (though the style guide section on writing extensions should link to it in github).

**Comment by oddhack** [comment]
I've updated the index page in internal gitlab and it will show up in the next spec update.

**Comment by oddhack** [comment]
@SaschaWillems first point has been addressed, I spun off #74 for the second point as while I don't mind taking the template out of the spec component, I'd like to have somewhere else to put it. I think this could be closed and discussion continued on #74 if you're comfortable with that.
