### ISSUE TITLE
Right-hand navigation for the "Layers & Extensions (Informative)" is too long

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Site#69]
The right-hand navigation for the "[Layers & Extensions (Informative)](https://docs.vulkan.org/spec/latest/appendices/extensions.html)" chapter is very long. In fact it's longer than the page's actual content, so it'll be cut off

![image](https://github.com/KhronosGroup/Vulkan-Site/assets/10283127/bbe8818c-a967-4172-8e24-dbab57c1d2e6)

This is caused by that navigation having all sub-chapters listed for every available extensions.

Is it possible to limit the level of captions for that navigation on this page, so that the right-hand navigation will only show links to the actual extensions?

**Comment by oddhack** [comment]
Will (hopefully) be fixed by internal MR 6436. But the right side will still be very long, with the number of extensions we have.
