### ISSUE TITLE
Depth Bias Computation equation isn't rendered

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-Site#7]
<https://registry.khronos.org/vulkan/site/spec/latest/chapters/primsrast.html#primsrast-depthbias-computation>

Currently looks like this:
![grafik](https://user-images.githubusercontent.com/49841484/230162637-ed5a8837-c942-476e-a0ea-376b4a61f913.png)

Same equation in the html spec:
![grafik](https://user-images.githubusercontent.com/49841484/230162861-83d4d498-7402-4a3a-99d3-efb1cc1e4ff4.png)

**Comment by oddhack** [comment]
I'm going to have to get into the guts of the @djencks/asciidoctor-mathjax extension to properly initialize the math parser. Unfortunately there's no way to affect this without rebuilding the extension, AFAICT.

**Comment by oddhack** [comment]
@DadSchoorse AFAICT this is fixed now - please reopen if you're still seeing this problem.
