### ISSUE TITLE
Filtering search by project

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-Site#76]
I've been trying out https://docs.vulkan.org/ as an alternative to the main spec, but one thing I've run into is that it would be nice to be able to filter search results by project.

I only want results from the spec itself, so anything from vulkan tutorials or vulkan samples if I search for "blending" gets in the way a bit.

I don't think this actually hides any results I want, but it does make it a bit harder to find what I'm after.

**Comment by oddhack** [comment]
This should be addressed by https://github.com/KhronosGroup/antora-ui-khronos/pull/7, which will show up the next time I do a spec update. It adds a checkbox that limits search to the current Antora "component" (more or less "project"). Please keep an eye on the site, which should be updated Friday morning, and close this if it addresses the need. You can also look at the latest build from CI, which is at https://github.khronos.org/Vulkan-Site/spec/latest/index.html, as a preview.

**Comment by baldurk** [comment]
Yep that's exactly what I'm after! The phrasing of the spec being a 'project' wasn't immediately intuitive but I understood exactly what it was doing after toggling the option.
