### ISSUE TITLE
I need Vulkan Version 1.1

### ISSUE THREAD

**Issue by Sherlock1914** [KhronosGroup/Vulkan-Site#78]
Hello Vulkan Support
I need an earlier or earlier version of the program (1.1) for it to work on my laptop
(Vulkan Version 1.1)

**Comment by oddhack** [comment]
You will need to ask the OS or GPU manufacturer for your laptop about driver support. Khronos does not supply Vulkan drivers. Suggest you try the vendor support forums for your GPU, or perhaps the Vulkan Discord server.
