### ISSUE TITLE
Remove "Edit this page" link?

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Site#89]
It looks like Antora automatically adds an "Edit this page" link to every page on the docs site:

![image](https://github.com/KhronosGroup/antora-ui-khronos/assets/10283127/81cd6e3a-fd69-4da9-aa07-8b3ef4382cf6)

This will open github's editor for that adoc page in the docs repo. But this only works for the spec and the guide, for other components like the tutorial, samples, the link redirects to a wrong URL.

Maybe we should generally remove that link?

**Comment by oddhack** [comment]
Done by #90 and site updated.
