### ISSUE TITLE
Issue with Documentation wrong Vulkan Version in chapters/features.html in code notes

### ISSUE THREAD

**Issue by DeCedDNA** [KhronosGroup/Vulkan-Site#91]
![Screenshot 2024-10-01 120912](https://github.com/user-attachments/assets/1f7f7a14-dbcb-4120-a3fb-47f97430f8d0)

The PhysicalDeviceVulkan11Features were provided by VULKAN_1_1 not 1_2

link to the hiccup: https://docs.vulkan.org/spec/latest/chapters/features.html

**Comment by oddhack** [comment]
Apparently my comment and closure did not get recorded. Maybe GH hiccuped after I hit the close button. In any event, this is not a mistake. The 11 structure was added in Vulkan 1.2 per https://github.com/KhronosGroup/Vulkan-Docs/issues/1437#issuecomment-765659397

**Comment by DeCedDNA** [comment]
Alright, thanks and I apologize for the unnecessary Issue.
