### ISSUE TITLE
[BUG] Image in proposal for VK_EXT_device_generated_commands broken

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Site#92]
The link for the (one) image in the proposal for the VK_EXT_device_generated_commands extension is broken:

![image](https://github.com/user-attachments/assets/7d1744e3-6e3e-47e0-9fe1-9aa62ead1de7)

Url: https://docs.vulkan.org/features/latest/features/proposals/VK_EXT_device_generated_commands.html#_proposal

**Comment by SaschaWillems** [comment]
Looks like it's already broken in the spec at https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_EXT_device_generated_commands.adoc

**Comment by oddhack** [comment]
https://github.com/KhronosGroup/Vulkan-Docs/pull/2441 fixes the github part of this (although it will be very easy for future proposals to overlook the requirements on how images are to be referenced - perhaps a CI check should be added for this although given this is only the second proposal image to ever be used, it won't happen often). The Antora part is a bit trickier and probably started failing when I split the proposals component off.

**Comment by oddhack** [comment]
I updated the PR with a fix for the Antora part as well and have merged it and verified the images in proposals now render correctly, although this won't show up on the docs site until the next spec update in a few days. Hopefully you or I will remember to close this at that point.

**Comment by SaschaWillems** [comment]
I can confirm that the image is now properly showing up on the docs site :)
