### ISSUE TITLE
[FEATURE] Fold the valid usage sections by default

### ISSUE THREAD

**Issue by goeiecool9999** [KhronosGroup/Vulkan-Site#94]
The valid usage sections take up a lot of space in the documentation. This hinders navigation and reading.
To illustrate this point there are two images below. I have highlighted parts of the text where the spec references itself.
The first image shows how far you have to scroll to get between the parts of the text. The second image shows a mock-up where I cut out the valid usage sections and added a little plus symbol that would function as a button to toggle the folding.
If GitHub's preview formatting matches the final publication (and if your monitor's scaling matches mine) it should be easy to compare.

Personally I find that having that information hidden makes it a lot easier to keep track of where I am in the document and improves my reading flow. The valid usage rules are really only relevant when you are interested in a specific part because you're about to use it for example. But if you're only reading the specification to learn about the API or are trying to find a specific section, it becomes tiresome to keep skipping over the valid usage sections.
Maybe it should be a user setting so people who are new to the spec don't overlook it altogether?

# Current website
![image](https://github.com/user-attachments/assets/1110cf58-8c29-43aa-a43b-7c8e24f35673)
# Suggestion mock-up
![image](https://github.com/user-attachments/assets/48ee9a6a-ab45-4e7e-8322-1c4315954918)

**Comment by goeiecool9999** [comment]
Apologies! I have just realised this is a duplicate of #22.

**Comment by oddhack** [comment]
I'm working on it. It's non-trivial to make it actually work in all browsers of interest, to provide a non-jarring behavior transition from current uses of the spec, and to make incoming links to anchors in collapsed sections, like VUIDs, automatically uncollapse - but making gradual progress.

**Comment by goeiecool9999** [comment]
> I'm working on it.

Awesome! Thank you very much. In the mean time I'm managing by using a uBlock origin element filter
For those interested:
``docs.vulkan.org##.sidebarblock:has(.title:has-text(Valid Usage))``
